name: Deployment

on:
  push:
    branches: [main]

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
        -   name: Set up Go
            uses: actions/setup-go@v5
        
        -   name: Checkout repository and submodules
            uses: actions/checkout@v4

        -   name: Build
            run: ./scripts/buildprod.sh
        

